import type { AuditResult } from './types';

export const MOCK_CLINICAL_NOTE = `Patient is a 67-year-old male presenting with acute exacerbation of chronic obstructive pulmonary disease (COPD). Patient reports significant dyspnea at rest, increased sputum production with purulent characteristics, and worsening cough over the past 72 hours. SpO2 on room air 84%. RR 26/min, accessory muscle use noted. CXR demonstrates hyperinflation with no acute infiltrate. ABG: pH 7.32, PaCO2 58, PaO2 52. Initiated high-flow O2 therapy, systemic corticosteroids (methylprednisolone 125mg IV), and broad-spectrum antibiotics (azithromycin + ceftriaxone). Bronchodilator therapy with albuterol and ipratropium every 4 hours. Patient requires close monitoring. Decision made to admit to ICU for ventilatory support consideration.`;

export const MOCK_AUDIT_RESULT: AuditResult = {
  runId: 'run_8f2a1b3c4d5e6f7a',
  decision: 'SUPPORTED',
  confidence: 87,
  billingCode: 'CPT 99285',
  policyReference: 'LCD L34559 - Emergency Medicine',
  runAt: '2024-01-15T14:23:07Z',
  requirementChecks: [
    {
      id: 'PR-01',
      requirement: 'Chief complaint documented',
      status: 'MET',
      evidence: 'Acute exacerbation of COPD with dyspnea at rest documented as presenting complaint.',
      explanation: 'The presenting complaint and related symptoms are explicitly documented.',
      severity: 'LOW',
    },
    {
      id: 'PR-02',
      requirement: 'High medical decision making (MDM) - extensive data review',
      status: 'MET',
      evidence: 'ABG interpretation, CXR review, and multi-system assessment documented.',
      explanation: 'The note includes diagnostic data review and clinical assessment supporting high MDM.',
      severity: 'MEDIUM',
    },
    {
      id: 'PR-03',
      requirement: 'High MDM - high risk of morbidity/mortality',
      status: 'MET',
      evidence: 'SpO2 84%, pH 7.32 acidosis, ICU admission decision documented.',
      explanation: 'Hypoxia, acidosis, and ICU disposition support high patient risk.',
      severity: 'HIGH',
    },
    {
      id: 'PR-04',
      requirement: 'Independent interpretation of diagnostic tests by treating physician',
      status: 'AMBIGUOUS',
      evidence: 'CXR result referenced but no explicit statement of independent interpretation.',
      explanation: 'The CXR finding is documented, but independent physician interpretation is unclear.',
      severity: 'MEDIUM',
    },
    {
      id: 'PR-05',
      requirement: 'Prescription drug management for new condition',
      status: 'MET',
      evidence: 'Methylprednisolone, azithromycin, ceftriaxone, albuterol, ipratropium initiated.',
      explanation: 'Medication management is clearly documented for the acute condition.',
      severity: 'MEDIUM',
    },
    {
      id: 'PR-06',
      requirement: 'Time-based billing or MDM documented if >60 min',
      status: 'NOT_MET',
      evidence: 'Total encounter time or start/stop times not documented in the note.',
      explanation: 'The note does not include time documentation needed for time-based billing.',
      severity: 'HIGH',
    },
  ],
  missingDocumentation: [
    {
      id: 'MD-01',
      severity: 'HIGH',
      title: 'Physician attestation of independent CXR interpretation',
      recommendation: 'Add explicit statement: "I reviewed and independently interpreted the chest radiograph demonstrating [findings]."',
    },
    {
      id: 'MD-02',
      severity: 'MEDIUM',
      title: 'Total encounter time / start-stop timestamps',
      recommendation: 'If time-based coding is intended, document total time in minutes or explicit start/end timestamps.',
    },
    {
      id: 'MD-03',
      severity: 'LOW',
      title: 'Allergy documentation absent from note',
      recommendation: 'Reference allergy list reviewed prior to prescribing antibiotics.',
    },
  ],
  extractedFacts: [
    { label: 'Age / Sex', value: '67-year-old male', evidence: 'Patient is a 67-year-old male' },
    { label: 'Primary Dx', value: 'Acute exacerbation COPD (J44.1)', evidence: 'acute exacerbation of chronic obstructive pulmonary disease (COPD)' },
    { label: 'SpO2 (room air)', value: '84%', evidence: 'SpO2 on room air 84%' },
    { label: 'Respiratory rate', value: '26/min', evidence: 'RR 26/min' },
    { label: 'ABG pH', value: '7.32 (acidosis)', evidence: 'ABG: pH 7.32' },
    { label: 'PaCO2', value: '58 mmHg (hypercapnia)', evidence: 'PaCO2 58' },
    { label: 'Interventions', value: 'O2 therapy, IV corticosteroids, antibiotics, bronchodilators', evidence: 'Initiated high-flow O2 therapy, systemic corticosteroids, and broad-spectrum antibiotics' },
    { label: 'Disposition', value: 'ICU admission for ventilatory support', evidence: 'Decision made to admit to ICU for ventilatory support consideration' },
    { label: 'CXR finding', value: 'Hyperinflation, no acute infiltrate', evidence: 'CXR demonstrates hyperinflation with no acute infiltrate' },
    { label: 'Risk level', value: 'High - acidosis, hypoxia, ICU-level care', evidence: 'SpO2 on room air 84%. Decision made to admit to ICU' },
  ],
  auditTrail: [
    {
      id: 'AT-01',
      label: 'CLAIM_INGESTED',
      description: 'Clinical note and billing data received',
      status: 'COMPLETE',
      timestamp: '14:23:07.001',
      detail: 'CPT 99285 - LCD L34559',
    },
    {
      id: 'AT-02',
      label: 'NLP_EXTRACTION',
      description: 'Clinical entity extraction via NLP',
      status: 'COMPLETE',
      timestamp: '14:23:07.312',
      detail: '10 entities extracted - 0 parse errors',
    },
    {
      id: 'AT-03',
      label: 'POLICY_LOOKUP',
      description: 'Policy requirements fetched',
      status: 'COMPLETE',
      timestamp: '14:23:07.518',
      detail: 'LCD L34559 - 6 requirements loaded',
    },
    {
      id: 'AT-04',
      label: 'REQUIREMENT_EVAL',
      description: 'Policy requirement evaluation',
      status: 'COMPLETE',
      timestamp: '14:23:08.104',
      detail: '4 Met - 1 Ambiguous - 1 Not Met',
    },
    {
      id: 'AT-05',
      label: 'DOCUMENTATION_GAP_ANALYSIS',
      description: 'Documentation gap analysis',
      status: 'COMPLETE',
      timestamp: '14:23:08.441',
      detail: '3 gaps identified - 1 high severity',
    },
    {
      id: 'AT-06',
      label: 'CONFIDENCE_SCORING',
      description: 'Confidence score computed',
      status: 'COMPLETE',
      timestamp: '14:23:08.709',
      detail: 'Score: 87% - Threshold: 80%',
    },
    {
      id: 'AT-07',
      label: 'VERDICT_ISSUED',
      description: 'Audit verdict finalized',
      status: 'COMPLETE',
      timestamp: '14:23:08.891',
      detail: 'SUPPORTED - Recommend approval',
    },
  ],
  rawAgentOutput: {
    model: 'claim-audit-agent-v2.1',
    runId: 'run_8f2a1b3c4d5e6f7a',
    input: {
      billingCode: 'CPT 99285',
      policyReference: 'LCD L34559',
      noteTokens: 187,
    },
    extraction: {
      entities: ['COPD exacerbation', 'SpO2 84%', 'pH 7.32', 'PaCO2 58', 'ICU admission', 'methylprednisolone', 'azithromycin', 'ceftriaxone', 'albuterol', 'ipratropium'],
      negations: [],
      uncertaintyMarkers: ['no acute infiltrate'],
    },
    policyEvaluation: {
      'PR-01': { result: 'MET', confidence: 0.98 },
      'PR-02': { result: 'MET', confidence: 0.93 },
      'PR-03': { result: 'MET', confidence: 0.95 },
      'PR-04': { result: 'AMBIGUOUS', confidence: 0.61 },
      'PR-05': { result: 'MET', confidence: 0.99 },
      'PR-06': { result: 'NOT_MET', confidence: 0.97 },
    },
    decision: 'SUPPORTED',
    confidenceScore: 0.87,
    flags: ['MISSING_PHYSICIAN_ATTESTATION_CXR', 'NO_TIME_DOCUMENTATION'],
    latencyMs: 1890,
  },
};



