import type { AuditResult } from './types';

export const MOCK_CLINICAL_NOTE = `Patient is a 67-year-old male presenting with acute exacerbation of chronic obstructive pulmonary disease (COPD). Patient reports significant dyspnea at rest, increased sputum production with purulent characteristics, and worsening cough over the past 72 hours. SpO2 on room air 84%. RR 26/min, accessory muscle use noted. CXR demonstrates hyperinflation with no acute infiltrate. ABG: pH 7.32, PaCO2 58, PaO2 52. Initiated high-flow O2 therapy, systemic corticosteroids (methylprednisolone 125mg IV), and broad-spectrum antibiotics (azithromycin + ceftriaxone). Bronchodilator therapy with albuterol and ipratropium every 4 hours. Patient requires close monitoring. Decision made to admit to ICU for ventilatory support consideration.`;

export const MOCK_AUDIT_RESULT: AuditResult = {
  verdict: 'Supported',
  confidence: 87,
  billingCode: 'CPT 99285',
  policyRef: 'LCD L34559 – Emergency Medicine',
  runAt: '2024-01-15T14:23:07Z',
  policyRequirements: [
    {
      id: 'PR-01',
      label: 'Chief complaint documented',
      status: 'Met',
      evidence: 'Acute exacerbation of COPD with dyspnea at rest documented as presenting complaint.',
    },
    {
      id: 'PR-02',
      label: 'High medical decision making (MDM) – extensive data review',
      status: 'Met',
      evidence: 'ABG interpretation, CXR review, and multi-system assessment documented.',
    },
    {
      id: 'PR-03',
      label: 'High MDM – high risk of morbidity/mortality',
      status: 'Met',
      evidence: 'SpO2 84%, pH 7.32 acidosis, ICU admission decision documented.',
    },
    {
      id: 'PR-04',
      label: 'Independent interpretation of diagnostic tests by treating physician',
      status: 'Ambiguous',
      evidence: 'CXR result referenced but no explicit statement of independent interpretation.',
    },
    {
      id: 'PR-05',
      label: 'Prescription drug management for new condition',
      status: 'Met',
      evidence: 'Methylprednisolone, azithromycin, ceftriaxone, albuterol, ipratropium initiated.',
    },
    {
      id: 'PR-06',
      label: 'Time-based billing or MDM documented if >60 min',
      status: 'Not Met',
      evidence: 'Total encounter time or start/stop times not documented in the note.',
    },
  ],
  missingDocumentation: [
    {
      id: 'MD-01',
      severity: 'High',
      item: 'Physician attestation of independent CXR interpretation',
      recommendation: 'Add explicit statement: "I reviewed and independently interpreted the chest radiograph demonstrating [findings]."',
    },
    {
      id: 'MD-02',
      severity: 'Medium',
      item: 'Total encounter time / start-stop timestamps',
      recommendation: 'If time-based coding is intended, document total time in minutes or explicit start/end timestamps.',
    },
    {
      id: 'MD-03',
      severity: 'Low',
      item: 'Allergy documentation absent from note',
      recommendation: 'Reference allergy list reviewed prior to prescribing antibiotics.',
    },
  ],
  clinicalFacts: [
    { label: 'Age / Sex', value: '67-year-old male' },
    { label: 'Primary Dx', value: 'Acute exacerbation COPD (J44.1)' },
    { label: 'SpO2 (room air)', value: '84%' },
    { label: 'Respiratory rate', value: '26/min' },
    { label: 'ABG pH', value: '7.32 (acidosis)' },
    { label: 'PaCO2', value: '58 mmHg (hypercapnia)' },
    { label: 'Interventions', value: 'O2 therapy, IV corticosteroids, antibiotics, bronchodilators' },
    { label: 'Disposition', value: 'ICU admission for ventilatory support' },
    { label: 'CXR finding', value: 'Hyperinflation, no acute infiltrate' },
    { label: 'Risk level', value: 'High – acidosis, hypoxia, ICU-level care' },
  ],
  auditTrail: [
    {
      id: 'AT-01',
      icon: 'Upload',
      action: 'CLAIM_INGESTED',
      label: 'Clinical note and billing data received',
      status: 'Complete',
      timestamp: '14:23:07.001',
      detail: 'CPT 99285 · LCD L34559',
    },
    {
      id: 'AT-02',
      icon: 'Psychology',
      action: 'NLP_EXTRACTION',
      label: 'Clinical entity extraction via NLP',
      status: 'Complete',
      timestamp: '14:23:07.312',
      detail: '10 entities extracted · 0 parse errors',
    },
    {
      id: 'AT-03',
      icon: 'Policy',
      action: 'POLICY_LOOKUP',
      label: 'Policy requirements fetched',
      status: 'Complete',
      timestamp: '14:23:07.518',
      detail: 'LCD L34559 · 6 requirements loaded',
    },
    {
      id: 'AT-04',
      icon: 'Rule',
      action: 'REQUIREMENT_EVAL',
      label: 'Policy requirement evaluation',
      status: 'Complete',
      timestamp: '14:23:08.104',
      detail: '4 Met · 1 Ambiguous · 1 Not Met',
    },
    {
      id: 'AT-05',
      icon: 'FindInPage',
      action: 'DOCUMENTATION_GAP_ANALYSIS',
      label: 'Documentation gap analysis',
      status: 'Complete',
      timestamp: '14:23:08.441',
      detail: '3 gaps identified · 1 high severity',
    },
    {
      id: 'AT-06',
      icon: 'Verified',
      action: 'CONFIDENCE_SCORING',
      label: 'Confidence score computed',
      status: 'Complete',
      timestamp: '14:23:08.709',
      detail: 'Score: 87% · Threshold: 80%',
    },
    {
      id: 'AT-07',
      icon: 'Gavel',
      action: 'VERDICT_ISSUED',
      label: 'Audit verdict finalized',
      status: 'Complete',
      timestamp: '14:23:08.891',
      detail: 'SUPPORTED · Recommend approval',
    },
  ],
  rawAgentOutput: {
    model: 'claim-audit-agent-v2.1',
    run_id: 'run_8f2a1b3c4d5e6f7a',
    input: {
      billing_code: 'CPT 99285',
      policy_ref: 'LCD L34559',
      note_tokens: 187,
    },
    extraction: {
      entities: ['COPD exacerbation', 'SpO2 84%', 'pH 7.32', 'PaCO2 58', 'ICU admission', 'methylprednisolone', 'azithromycin', 'ceftriaxone', 'albuterol', 'ipratropium'],
      negations: [],
      uncertainty_markers: ['no acute infiltrate'],
    },
    policy_eval: {
      'PR-01': { result: 'MET', confidence: 0.98 },
      'PR-02': { result: 'MET', confidence: 0.93 },
      'PR-03': { result: 'MET', confidence: 0.95 },
      'PR-04': { result: 'AMBIGUOUS', confidence: 0.61 },
      'PR-05': { result: 'MET', confidence: 0.99 },
      'PR-06': { result: 'NOT_MET', confidence: 0.97 },
    },
    verdict: 'SUPPORTED',
    confidence_score: 0.87,
    flags: ['MISSING_PHYSICIAN_ATTESTATION_CXR', 'NO_TIME_DOCUMENTATION'],
    latency_ms: 1890,
  },
};
